### ISSUE TITLE
Add setup verification

### ISSUE THREAD

**Issue by swsnr** [Sarcasm/flycheck-irony#1]
Hello,

Flycheck has a `flycheck-verify-setup` command which helps users check whether Flycheck is correctly setup.  Essentially it shows all syntax checkers that could apply to the current buffer, and shows potential problems.  3rd party checkers can add their own diagnostics with a `:verify` function (see [flycheck-ocaml](https://github.com/flycheck/flycheck-ocaml/blob/c89fb8a14c59f47827995effb014f4fb46b4022e/flycheck-ocaml.el#L145)) for example).

Just wanted to make you aware of this feature.  Supporting it in this package might help users to get it working.  Note that if you add `:verify` function, you should add `:modes`, too, to make best use of it.

Greetings

**Comment by Sarcasm** [comment]
Thanks, will do!
