### ISSUE TITLE
Fringe indicators have wrong colors

### ISSUE THREAD

**Issue by jwintz** [Sarcasm/flycheck-irony#13]
Hello Guillaume,

I use `irony-mode` with `company-irony` and `flycheck-irony`.

I have setup `flycheck-irony` very simply:

``` lisp
(require 'flycheck)
(require 'flycheck-irony)

(eval-after-load 'flycheck '(add-hook 'flycheck-mode-hook 'flycheck-irony-setup))

(add-hook    'c-mode-hook 'flycheck-mode)
(add-hook  'c++-mode-hook 'flycheck-mode)
(add-hook 'objc-mode-hook 'flycheck-mode)
```

I have disabled all flycheck fringe faces in my theme, or any fringe bitmap in my config to get a vanilla setup. 

However, fringe indicators are all red (for errors as well as for warnings and info), while inline waves are colored correctly.

![screen shot 2015-11-27 at 20 37 53](https://cloud.githubusercontent.com/assets/3277054/11447569/3befd486-9548-11e5-8f3d-5e2cbcf373b9.png)
- Is that a `flycheck-irony` issue ?
- Is that a `irony-mode` issue ?
- Is that a `flycheck` issue ?

Many thanks !

**Comment by Sarcasm** [comment]
Looks like the way flycheck normal behavior, in the screenshot of their homepage it seems to be the same: http://www.flycheck.org/

**Comment by jwintz** [comment]
Their screenshots only show **warnings**. See spacemacs repository for an example where flycheck shows fringe's indicators colored according to their types (info, warning or error).

![spacemacs-python](https://cloud.githubusercontent.com/assets/3277054/11447700/f536fb3e-954a-11e5-8ec2-7c8b656b32b1.png)

**Comment by Sarcasm** [comment]
Interesting. Well you should probably try with another mode, elisp or something like that to see if you have the same issue. If you have it then I suggest you to ask the flycheck folks about that. If you don't I can take a deeper look but if you look at flycheck-irony code, which is very short, you will notice that nothing specific is done w.r.t the fringes.

**Comment by jwintz** [comment]
Very good idea. I have disabled `flycheck-inrony` and enabled `flycheck` for `emacs-lisp-mode`. The issue remains.

![screen shot 2015-11-27 at 22 10 02](https://cloud.githubusercontent.com/assets/3277054/11448209/c7fc3f36-9553-11e5-9060-7955bcd1251c.png)

So it is a flycheck issue. I am closing this ticket.

Thanks for your awesome packages !
